GDC-755: Перенести репозитории в gazprom-neft
gazprom-neft/consta-widgets-utils pull request #2
Opened 2020-09-11 10:01 UTC by graberzz

## Задача
- ссылка на jira: __HERE_JIRA_ID__

2020-09-18 08:00 UTC, al-fyodorov requested changes

2020-09-18 08:00 UTC, al-fyodorov commented on package.json
> +    "@consta/widgets-configs": "1.1.2-0",
Тут странно, версия указанна `1.1.2-0`, а в `yarn.lock` напротив `0.2.23`, которая тянется не с NPM Registry, а с GitHub Registry, разве так и должно быть?

2020-09-18 08:00 UTC, al-fyodorov commented on package.json
> +  "version": "0.2.14-0",
В другом PR уже был подобный вопрос, но пока так и не понятно, есть ли смысл обновлять версию в PR без публикации, да и еще на странный номер.

2020-09-18 08:00 UTC, al-fyodorov commented on package.json
>    "author": "CSSSR",
[note]
Я бы еще дополнительно уточнил по поводу указания авторства и лицензии, так как Consta относится к Газпрому, то наверное все эти наработки должны иметь авторство Газпрома, но это не точно.

2020-09-18 08:26 UTC, graberzz commented on package.json
> +  "version": "0.2.14-0",
Ответил в другом ПР https://github.com/gazprom-neft/consta-widgets-configs/pull/2#discussion_r490784803

2020-09-18 08:32 UTC, graberzz commented on package.json
> +    "@consta/widgets-configs": "1.1.2-0",
Да, ошибка. Обновил yarn.lock

2020-09-18 08:33 UTC, graberzz commented on package.json
>    "author": "CSSSR",
Выпилил эти поля пока

2020-09-21 07:35 UTC, nekitk requested changes

2020-09-21 07:35 UTC, nekitk commented on package.json
> +  "version": "0.2.14-0",
тут тоже не нужно поднимать версию в пул-реквесте — нужно делать это в мастере после того, как пул-ревест вмёржим

2020-09-21 09:38 UTC, merged